/*************************************************************************
 *
 * Copyright (c) 2018-2022, Lawrence Livermore National Security, LLC.
 * See the top-level LICENSE file for details.
 * Produced at the Lawrence Livermore National Laboratory
 *
 * SPDX-License-Identifier: MIT
 *
 ************************************************************************/
#ifndef _DIRECTIONS_H_
#define _DIRECTIONS_H_

namespace Loki {

/**
 * Enumerations for directions.
 */
enum {X1, X2, V1, CDIM=V1, V2, PDIM};

enum {LO=0, HI};

} // end namespace Loki

#endif
